### ISSUE TITLE
Notice: Undefined property: stdClass::$editor in ... \MapBuilder\admin\views\maps\tmpl\list_isis.php on line 152

### ISSUE THREAD

**Issue by terryburg** [joomlachicagoloop/MapBuilder#11]
Error notice on map list when a map is checked out.

Offending line in template file(s):

if($row->checked_out){
                            echo JHtml::_('jgrid.checkedout', $i, $row->editor, $row->checked_out_time, 'maps.', $canCheckin);
                            echo "<span class=\"title\">".JText::_( $row->map_name)."</span>";

Cause: SQL in admin/models/maps.php and markers.php did not have join to users table to get the userid of the user(editor) associated with the checkout in the user_id field of maps table. Assuming retrieving that was the original intent?

I picked this little issue to fix as a test to make sure I am doing the git & github flow correctly, as well as following team policies/procedures.

Pull request to follow.

**Comment by subtext** [comment]
Changes applied via pull request.
